# Cold pool Table 2 - EBS and NBS Survey Start/End Times and Number of Samples per Region Per Year (1982-2019, 2021)
# Created by: Nicole Charriere and Sean Rohan
# Contact: nicole.charriere@noaa.gov
# Created: 2022-04-07
# Modified: 2022-04-08 

#Load required libraries
library(coldpool)
library(tidyverse)
library(dplyr)
library(lubridate)

#Connect to AFSC Oracle database and assign get_connected function to channel
?get_connected
?coldpool::get_data
channel <- coldpool::get_connected(schema = "AFSC")

#Get gear temperature data in .csv form for all EBS and NBS hauls from .sql script in coldpool package
coldpool::get_data(channel)

#View .csv file generated by coldpool::get_data function
ebs_nbs_temps_full <- read.csv("data/ebs_nbs_temperature_full_area.csv")
ebs_nbs_temps_full

#

ebs_nbs_temps_full <- filter(ebs_nbs_temps_full, survey_definition_id == 143) %>%
  dplyr::bind_rows(read.csv("data/index_hauls_temperature_data.csv"))
ebs_nbs_temps_full

table(ebs_nbs_temps_full$stratum, ebs_nbs_temps_full$survey_definition_id)

#NAs appear in data set. Filter .csv for surface temperatures not equal to NA (!is.na)
ebs_nbs_temps_filt <-filter(ebs_nbs_temps_full, !is.na(surface_temperature))
ebs_nbs_temps_filt

#Get .csv column names to reorganize
colnames(ebs_nbs_temps_filt)

#Reorganize .csv column names in order of year,survey_definition_id, start_time, gear_temperature and surface_temperature

ebs_nbs_temps_sum <- dplyr::select(ebs_nbs_temps_filt, year, survey_definition_id, start_time, gear_temperature, surface_temperature) %>%
  dplyr::group_by(year, survey_definition_id, start_time, gear_temperature, surface_temperature) %>%
  dplyr::summarize()
ebs_nbs_temps_sum

#Find start and end dates to surveys from .csv
#Convert start_time column to Anchorage time zone

ebs_nbs_temps_sum$start_time <- as.POSIXct(ebs_nbs_temps_sum$start_time, tz = "America/Anchorage")
ebs_nbs_temps_sum$start_time

#Find day of the year (yday) for start_time and add column to ebs_nbs_temps_sum table

ebs_nbs_temps_sum$yday <- lubridate::yday(ebs_nbs_temps_sum$start_time)
ebs_nbs_temps_sum$yday
ebs_nbs_temps_sum

#Group ebs_nbs_temps_sum table by year and survey_definition_id. Find 1) min start time (survey start date), 2) max start time (survey end date) and number of temperature samples per year (n).

start_end_num <- ebs_nbs_temps_sum %>% 
  dplyr::group_by(year, survey_definition_id) %>% 
  dplyr::summarize(survey_start_date = min(start_time), survey_end_date = max(start_time), temp_samples_per_year = n()) %>%
  as.data.frame()
start_end_num

#Rename survey_definition_id column to region

nebs_start_end_num <- dplyr::rename(start_end_num, region = survey_definition_id)
nebs_start_end_num

#Change survey_start_times$survey_definition_id class to character 

base::sapply(nebs_start_end_num$region, class)
nebs_start_end_num$region <- as.character(nebs_start_end_num$region)
base::sapply(nebs_start_end_num$region, class)

#Rename survey_definition_id = 98 to "EBS"; and 143 to "NBS"

nebs_start_end_num$region[nebs_start_end_num$region == "98"] <- "EBS"
nebs_start_end_num$region[nebs_start_end_num$region == "143"] <- "NBS"
nebs_start_end_num$region

#Convert start and end times to month and day

lubridate::month(nebs_start_end_num$survey_start_date, label = TRUE, abbr = TRUE)
lubridate::day(nebs_start_end_num$survey_start_date)

nebs_start_end_num$survey_start_date <- paste(lubridate::month(nebs_start_end_num$survey_start_date, label = TRUE, abbr = TRUE), lubridate::day(nebs_start_end_num$survey_start_date))

nebs_start_end_num$survey_end_date <- paste(lubridate::month(nebs_start_end_num$survey_end_date, label = TRUE, abbr = TRUE), lubridate::day(nebs_start_end_num$survey_end_date))

View(nebs_start_end_num)

?pivot_wider


#Write .csv with year, region, start and end times, and number of temperature samples

write.csv(nebs_start_end_num, file = "survey_dates_and_samples.csv", row.names = FALSE)

#Find average # of survey days

survey_start_end_days <- ebs_nbs_temps_sum %>% 
  dplyr::group_by(year) %>% 
  dplyr::summarize(min_day = min(yday), max_day = max(yday)) %>%
  as.data.frame()
survey_start_end_days

mean((survey_start_end_days$max_day - survey_start_end_days$min_day)+1)
