
#Load required libraries
library(coldpool)
library(tidyverse)
library(dplyr)
library(lubridate)

#Connect to AFSC Oracle database and assign get_connected function to channel
?get_connected
?coldpool::get_data
channel <- coldpool::get_connected(schema = "AFSC")

#Get gear temperature data in .csv form for all EBS and NBS hauls from .sql script in coldpool package
coldpool::get_data(channel)

#View .csv file generated by coldpool::get_data function
ebs_nbs_temps_full <- read.csv("data/ebs_nbs_temperature_full_area.csv")
ebs_nbs_temps_full

#NAs appear in data set. Filter .csv for surface temperatures not equal to NA (!is.na)
ebs_nbs_temps_filt <-filter(ebs_nbs_temps_full, !is.na(surface_temperature))
ebs_nbs_temps_filt

#Get .csv column names to reorganize
colnames(ebs_nbs_temps_filt)

#Reorganize .csv column names in order of year, cruise, survey_definition_id, stratum, stationid, start_time, latitude, longitude, haul_type, performance, gear_temperature, surface_temperature, bottom_depth

ebs_nbs_temps_sum <- dplyr::select(ebs_nbs_temps_filt, year, cruise, survey_definition_id, stratum, stationid, start_time, latitude, longitude, haul_type, performance, gear_temperature, surface_temperature, bottom_depth) %>%
  dplyr::group_by(year, cruise, survey_definition_id, stratum, stationid, start_time, latitude, longitude, haul_type, performance, gear_temperature, surface_temperature, bottom_depth) %>%
  dplyr::summarize()
ebs_nbs_temps_sum

#Find start and end dates to surveys from .csv
#Filter and select for year, cruise, stratum, stationid, and start_time from ebs_nbs_temps_full

ebs_nbs_temps_full_start_time_filt <- dplyr::select(ebs_nbs_temps_full, year, cruise, stratum, stationid, start_time)
ebs_nbs_temps_full_start_time_filt

#Convert start_time column to Anchorage time zone

ebs_nbs_temps_full_start_time_filt$start_time <- as.POSIXct(ebs_nbs_temps_full_start_time_filt$start_time, tz = "America/Anchorage")
ebs_nbs_temps_full_start_time_filt$start_time

#Find day of the year (yday) for start_time and add column to esb_nbs_full_start_time_filt table

ebs_nbs_temps_full_start_time_filt$yday <- lubridate::yday(ebs_nbs_temps_full_start_time_filt$start_time)
ebs_nbs_temps_full_start_time_filt$yday
ebs_nbs_temps_full_start_time_filt

#Group ebs_nbs_temps_full_start_time_filt table by year and find 1) min start time (survey start date), 2) max start time (survey end date) and number of temperature samples per year (n)

survey_start_end_times <- ebs_nbs_temps_full_start_time_filt %>% 
  dplyr::group_by(year) %>% 
  dplyr::summarize(survey_start_date = min(start_time), survey_end_date = max(start_time), temp_samples_per_year = n()) %>%
  as.data.frame()
survey_start_end_times

#Convert start and end times to month and day

lubridate::month(survey_start_end_times$survey_start_date, label = TRUE, abbr = TRUE)
lubridate::day(survey_start_end_times$survey_start_date)

survey_start_end_times$survey_start_date <- paste(lubridate::month(survey_start_end_times$survey_start_date, label = TRUE, abbr = TRUE), lubridate::day(survey_start_end_times$survey_start_date))

survey_start_end_times$survey_end_date <- paste(lubridate::month(survey_start_end_times$survey_end_date, label = TRUE, abbr = TRUE), lubridate::day(survey_start_end_times$survey_end_date))
  
View(survey_start_end_times)

#Write .csv with year, start and end times, and number of temperature samples

write.csv(survey_start_end_times, file = "survey_dates_and_samples.csv", row.names = FALSE)

#Find average # of survey days

survey_start_end_days <- ebs_nbs_temps_full_start_time_filt %>% 
  dplyr::group_by(year) %>% 
  dplyr::summarize(min_day = min(yday), max_day = max(yday)) %>%
  as.data.frame()
survey_start_end_days

ave(survey_start_end_days$max_day - survey_start_end_days$min_day)